name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker cache
        uses: actions/cache@v2
        with:
          path: dockerfile_rails.tar
          key: dockerfile

      - name: docker load
        run: test -f dockerfile_rails.tar && docker load < dockerfile_rails.tar || true

      - name: docker build
        run: docker build -f dockerfile_rails . -t edimossilva/boilerplate --cache-from "edimossilva/boilerplate"

      - name: docker save
        run: docker save edimossilva/boilerplate > dockerfile_rails.tar

      - name: start server
        run: docker-compose up -d

      - name: lint
        run: docker-compose exec -T boilerplate_server bundle exec rubocop

      - name: test
        run: docker-compose exec -T boilerplate_server bundle exec rspec
